[infer] Prevent deserialization errors with CustomDiff for Config
This commit prevents deserialization errors when users add a `infer.CustomConfig`
implementation to their config struct, which introduces the need to deserialize state
into the config struct.

It results in annoying errors like this:

    error: rpc error: code = Unknown desc = 2 failures decoding:
        __pulumi-go-provider-infer: Unrecognized field '__pulumi-go-provider-infer' on 'config.Config'
        __pulumi-go-provider-version: Unrecognized field '__pulumi-go-provider-version' on 'config.Config'